In [1]:
!pip install pandas numpy matplotlib scikit-learn tqdm

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2.3.1)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2.3.1)
Requirement already satisfied: matplotlib in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (3.10.0)
Requirement already satisfied: scikit-learn in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (1.6.1)
Requirement already satisfied: tqdm in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (4.67.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2025.1)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (3.2.1)
Requirement already satisfied: scipy>=1.6.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-learn) (1.15.2)
Requirement already satisfied: joblib>=1.2.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import json
import pandas as pd
import numpy as np

with open('user-wallet-transactions.json', 'r') as f:
    data = json.load(f)

df = pd.DataFrame(data)
df.head(10)

,_id,userWallet,network,protocol,txHash,logId,timestamp,blockNumber,action,actionData,__v,createdAt,updatedAt
0,{'$oid': '681d38fed63812d4655f571a'},0x00000000001accfa9cef68cf5371a23025b6d4b6,polygon,aave_v2,0x695c69acf608fbf5d38e48ca5535e118cc213a89e3d6...,0x695c69acf608fbf5d38e48ca5535e118cc213a89e3d6...,1629178166,1629178166,deposit,"{'type': 'Deposit', 'amount': '2000000000', 'a...",0,{'$date': '2025-05-08T23:06:39.465Z'},{'$date': '2025-05-08T23:06:39.465Z'}
1,{'$oid': '681aa70dd6df53021cc6f3c0'},0x000000000051d07a4fb3bd10121a343d85818da6,polygon,aave_v2,0xe6fc162c86b2928b0ba9b82bda672763665152b9de9d...,0xe6fc162c86b2928b0ba9b82bda672763665152b9de9d...,1621525013,1621525013,deposit,"{'type': 'Deposit', 'amount': '145000000000000...",0,{'$date': '2025-05-07T00:19:26.159Z'},{'$date': '2025-05-07T00:19:26.159Z'}
2,{'$oid': '681d04c2d63812d4654c733e'},0x000000000096026fb41fc39f9875d164bd82e2dc,polygon,aave_v2,0xe2d7eb815c89331a734ed6f204a06c385a1b39040baa...,0xe2d7eb815c89331a734ed6f204a06c385a1b39040baa...,1627118913,1627118913,deposit,"{'type': 'Deposit', 'amount': '100000000000000...",0,{'$date': '2025-05-08T19:23:47.877Z'},{'$date': '2025-05-08T19:23:47.877Z'}
3,{'$oid': '681d133bd63812d46551b6ef'},0x000000000096026fb41fc39f9875d164bd82e2dc,polygon,aave_v2,0x0d63a2eacd82b82f868db825ea7385e6bd8d046ee729...,0x0d63a2eacd82b82f868db825ea7385e6bd8d046ee729...,1627773318,1627773318,deposit,"{'type': 'Deposit', 'amount': '400000000000000...",0,{'$date': '2025-05-08T20:25:33.141Z'},{'$date': '2025-05-08T20:25:33.141Z'}
4,{'$oid': '681899e4ba49fc91cf2f4454'},0x0000000000e189dd664b9ab08a33c4839953852c,polygon,aave_v2,0x590eabb812c5006a6f4766f44e6e9d3ad0b5b563de69...,0x590eabb812c5006a6f4766f44e6e9d3ad0b5b563de69...,1618845907,1618845907,redeemunderlying,"{'type': 'RedeemUnderlying', 'amount': '501548...",0,{'$date': '2025-05-05T10:58:45.934Z'},{'$date': '2025-05-05T10:58:45.934Z'}
5,{'$oid': '681899e4ba49fc91cf2f444b'},0x0000000000e189dd664b9ab08a33c4839953852c,polygon,aave_v2,0xf7088e777a37e0229becd726f1c5f472ddec0324b2e6...,0xf7088e777a37e0229becd726f1c5f472ddec0324b2e6...,1618845871,1618845871,redeemunderlying,"{'type': 'RedeemUnderlying', 'amount': '106163...",0,{'$date': '2025-05-05T10:58:45.934Z'},{'$date': '2025-05-05T10:58:45.934Z'}
6,{'$oid': '681899e4ba49fc91cf2f4464'},0x0000000000e189dd664b9ab08a33c4839953852c,polygon,aave_v2,0x4b49959659c5f2c78dec0e526303b9840cea68d25f8e...,0x4b49959659c5f2c78dec0e526303b9840cea68d25f8e...,1618845985,1618845985,redeemunderlying,"{'type': 'RedeemUnderlying', 'amount': '500553...",0,{'$date': '2025-05-05T10:58:45.940Z'},{'$date': '2025-05-05T10:58:45.940Z'}
7,{'$oid': '681899e4ba49fc91cf2f4442'},0x0000000000e189dd664b9ab08a33c4839953852c,polygon,aave_v2,0x8579a83cac34a62049a622b0bee09d9e7d43edec7eca...,0x8579a83cac34a62049a622b0bee09d9e7d43edec7eca...,1618845797,1618845797,redeemunderlying,"{'type': 'RedeemUnderlying', 'amount': '448924...",0,{'$date': '2025-05-05T10:58:45.934Z'},{'$date': '2025-05-05T10:58:45.934Z'}
8,{'$oid': '681899e4ba49fc91cf2f4a2e'},0x0000000000e189dd664b9ab08a33c4839953852c,polygon,aave_v2,0x72edddf6f791c284cfc8e743b07a30c081c735f37a39...,0x72edddf6f791c284cfc8e743b07a30c081c735f37a39...,1618859461,1618859461,redeemunderlying,"{'type': 'RedeemUnderlying', 'amount': '9995',...",0,{'$date': '2025-05-05T10:58:46.045Z'},{'$date': '2025-05-05T10:58:46.045Z'}
9,{'$oid': '68189a50ba49fc91cf2f5f33'},0x0000000000e189dd664b9ab08a33c4839953852c,polygon,aave_v2,0x39a01414b6586052600a913f991f79a685e4224c2763...,0x39a01414b6586052600a913f991f79a685e4224c2763...,1618920577,1618920577,redeemunderlying,"{'type': 'RedeemUnderlying', 'amount': '689721...",0,{'$date': '2025-05-05T11:00:35.232Z'},{'$date': '2025-05-05T11:00:35.232Z'}

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 13 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   _id          100000 non-null  object
 1   userWallet   100000 non-null  object
 2   network      100000 non-null  object
 3   protocol     100000 non-null  object
 4   txHash       100000 non-null  object
 5   logId        100000 non-null  object
 6   timestamp    100000 non-null  int64
 7   blockNumber  100000 non-null  int64
 8   action       100000 non-null  object
 9   actionData   100000 non-null  object
 10  __v          100000 non-null  int64
 11  createdAt    100000 non-null  object
 12  updatedAt    100000 non-null  object
dtypes: int64(3), object(10)
memory usage: 9.9+ MB

In [4]:
df.describe()

          timestamp   blockNumber       __v
count  1.000000e+05  1.000000e+05  100000.0
mean   1.623891e+09  1.623891e+09       0.0
std    3.016214e+06  3.016214e+06       0.0
min    1.617210e+09  1.617210e+09       0.0
25%    1.621585e+09  1.621585e+09       0.0
50%    1.623415e+09  1.623415e+09       0.0
75%    1.626057e+09  1.626057e+09       0.0
max    1.630605e+09  1.630605e+09       0.0

In [5]:
df.isnull().sum()

_id            0
userWallet     0
network        0
protocol       0
txHash         0
logId          0
timestamp      0
blockNumber    0
action         0
actionData     0
__v            0
createdAt      0
updatedAt      0
dtype: int64

In [6]:
df['timestamp'] = pd.to_datetime(df['timestamp'], unit='s')

In [7]:
df.head()

,_id,userWallet,network,protocol,txHash,logId,timestamp,blockNumber,action,actionData,__v,createdAt,updatedAt
0,{'$oid': '681d38fed63812d4655f571a'},0x00000000001accfa9cef68cf5371a23025b6d4b6,polygon,aave_v2,0x695c69acf608fbf5d38e48ca5535e118cc213a89e3d6...,0x695c69acf608fbf5d38e48ca5535e118cc213a89e3d6...,2021-08-17 05:29:26,1629178166,deposit,"{'type': 'Deposit', 'amount': '2000000000', 'a...",0,{'$date': '2025-05-08T23:06:39.465Z'},{'$date': '2025-05-08T23:06:39.465Z'}
1,{'$oid': '681aa70dd6df53021cc6f3c0'},0x000000000051d07a4fb3bd10121a343d85818da6,polygon,aave_v2,0xe6fc162c86b2928b0ba9b82bda672763665152b9de9d...,0xe6fc162c86b2928b0ba9b82bda672763665152b9de9d...,2021-05-20 15:36:53,1621525013,deposit,"{'type': 'Deposit', 'amount': '145000000000000...",0,{'$date': '2025-05-07T00:19:26.159Z'},{'$date': '2025-05-07T00:19:26.159Z'}
2,{'$oid': '681d04c2d63812d4654c733e'},0x000000000096026fb41fc39f9875d164bd82e2dc,polygon,aave_v2,0xe2d7eb815c89331a734ed6f204a06c385a1b39040baa...,0xe2d7eb815c89331a734ed6f204a06c385a1b39040baa...,2021-07-24 09:28:33,1627118913,deposit,"{'type': 'Deposit', 'amount': '100000000000000...",0,{'$date': '2025-05-08T19:23:47.877Z'},{'$date': '2025-05-08T19:23:47.877Z'}
3,{'$oid': '681d133bd63812d46551b6ef'},0x000000000096026fb41fc39f9875d164bd82e2dc,polygon,aave_v2,0x0d63a2eacd82b82f868db825ea7385e6bd8d046ee729...,0x0d63a2eacd82b82f868db825ea7385e6bd8d046ee729...,2021-07-31 23:15:18,1627773318,deposit,"{'type': 'Deposit', 'amount': '400000000000000...",0,{'$date': '2025-05-08T20:25:33.141Z'},{'$date': '2025-05-08T20:25:33.141Z'}
4,{'$oid': '681899e4ba49fc91cf2f4454'},0x0000000000e189dd664b9ab08a33c4839953852c,polygon,aave_v2,0x590eabb812c5006a6f4766f44e6e9d3ad0b5b563de69...,0x590eabb812c5006a6f4766f44e6e9d3ad0b5b563de69...,2021-04-19 15:25:07,1618845907,redeemunderlying,"{'type': 'RedeemUnderlying', 'amount': '501548...",0,{'$date': '2025-05-05T10:58:45.934Z'},{'$date': '2025-05-05T10:58:45.934Z'}

In [14]:

df.head()

,userWallet,network,protocol,txHash,logId,timestamp,blockNumber,action,actionData,createdAt
0,0x00000000001accfa9cef68cf5371a23025b6d4b6,polygon,aave_v2,0x695c69acf608fbf5d38e48ca5535e118cc213a89e3d6...,0x695c69acf608fbf5d38e48ca5535e118cc213a89e3d6...,2021-08-17 05:29:26,1629178166,deposit,"{'type': 'Deposit', 'amount': '2000000000', 'a...",{'$date': '2025-05-08T23:06:39.465Z'}
1,0x000000000051d07a4fb3bd10121a343d85818da6,polygon,aave_v2,0xe6fc162c86b2928b0ba9b82bda672763665152b9de9d...,0xe6fc162c86b2928b0ba9b82bda672763665152b9de9d...,2021-05-20 15:36:53,1621525013,deposit,"{'type': 'Deposit', 'amount': '145000000000000...",{'$date': '2025-05-07T00:19:26.159Z'}
2,0x000000000096026fb41fc39f9875d164bd82e2dc,polygon,aave_v2,0xe2d7eb815c89331a734ed6f204a06c385a1b39040baa...,0xe2d7eb815c89331a734ed6f204a06c385a1b39040baa...,2021-07-24 09:28:33,1627118913,deposit,"{'type': 'Deposit', 'amount': '100000000000000...",{'$date': '2025-05-08T19:23:47.877Z'}
3,0x000000000096026fb41fc39f9875d164bd82e2dc,polygon,aave_v2,0x0d63a2eacd82b82f868db825ea7385e6bd8d046ee729...,0x0d63a2eacd82b82f868db825ea7385e6bd8d046ee729...,2021-07-31 23:15:18,1627773318,deposit,"{'type': 'Deposit', 'amount': '400000000000000...",{'$date': '2025-05-08T20:25:33.141Z'}
4,0x0000000000e189dd664b9ab08a33c4839953852c,polygon,aave_v2,0x590eabb812c5006a6f4766f44e6e9d3ad0b5b563de69...,0x590eabb812c5006a6f4766f44e6e9d3ad0b5b563de69...,2021-04-19 15:25:07,1618845907,redeemunderlying,"{'type': 'RedeemUnderlying', 'amount': '501548...",{'$date': '2025-05-05T10:58:45.934Z'}

In [15]:

df.drop(columns=['logId'])

,userWallet,network,protocol,txHash,timestamp,blockNumber,action,actionData,createdAt
0,0x00000000001accfa9cef68cf5371a23025b6d4b6,polygon,aave_v2,0x695c69acf608fbf5d38e48ca5535e118cc213a89e3d6...,2021-08-17 05:29:26,1629178166,deposit,"{'type': 'Deposit', 'amount': '2000000000', 'a...",{'$date': '2025-05-08T23:06:39.465Z'}
1,0x000000000051d07a4fb3bd10121a343d85818da6,polygon,aave_v2,0xe6fc162c86b2928b0ba9b82bda672763665152b9de9d...,2021-05-20 15:36:53,1621525013,deposit,"{'type': 'Deposit', 'amount': '145000000000000...",{'$date': '2025-05-07T00:19:26.159Z'}
2,0x000000000096026fb41fc39f9875d164bd82e2dc,polygon,aave_v2,0xe2d7eb815c89331a734ed6f204a06c385a1b39040baa...,2021-07-24 09:28:33,1627118913,deposit,"{'type': 'Deposit', 'amount': '100000000000000...",{'$date': '2025-05-08T19:23:47.877Z'}
3,0x000000000096026fb41fc39f9875d164bd82e2dc,polygon,aave_v2,0x0d63a2eacd82b82f868db825ea7385e6bd8d046ee729...,2021-07-31 23:15:18,1627773318,deposit,"{'type': 'Deposit', 'amount': '400000000000000...",{'$date': '2025-05-08T20:25:33.141Z'}
4,0x0000000000e189dd664b9ab08a33c4839953852c,polygon,aave_v2,0x590eabb812c5006a6f4766f44e6e9d3ad0b5b563de69...,2021-04-19 15:25:07,1618845907,redeemunderlying,"{'type': 'RedeemUnderlying', 'amount': '501548...",{'$date': '2025-05-05T10:58:45.934Z'}
...,...,...,...,...,...,...,...,...,...
99995,0x06192f889f17bf2aff238d08d8c26cbcfcc7b45a,polygon,aave_v2,0x7c94fbaff37d45ed220e4eeac4e7f14f3476af596d12...,2021-06-11 14:20:45,1623421245,repay,"{'type': 'Repay', 'amount': '19724448273', 'as...",{'$date': '2025-05-08T10:19:50.145Z'}
99996,0x06192f889f17bf2aff238d08d8c26cbcfcc7b45a,polygon,aave_v2,0x04046c738ffa8a64323e0b8cb4b7a97883c722728e98...,2021-06-13 04:32:59,1623558779,redeemunderlying,"{'type': 'RedeemUnderlying', 'amount': '200000...",{'$date': '2025-05-08T10:54:21.390Z'}
99997,0x06192f889f17bf2aff238d08d8c26cbcfcc7b45a,polygon,aave_v2,0x77eab9a16e1b49a53365882b82786cf86263e73b358e...,2021-06-13 04:39:51,1623559191,deposit,"{'type': 'Deposit', 'amount': '199401391185794...",{'$date': '2025-05-08T10:54:21.403Z'}
99998,0x06192f889f17bf2aff238d08d8c26cbcfcc7b45a,polygon,aave_v2,0xf170ce9fed71fa7b8221f08fe8a601c5bf84b6f8e724...,2021-06-13 04:43:37,1623559417,borrow,"{'type': 'Borrow', 'amount': '4000000000', 'as...",{'$date': '2025-05-08T10:54:21.411Z'}
99999,0x06192f889f17bf2aff238d08d8c26cbcfcc7b45a,polygon,aave_v2,0x5f4f772a0fcf1efae834c739852ed701551158d7a7c0...,2021-06-15 08:26:17,1623745577,borrow,"{'type': 'Borrow', 'amount': '7000000000000000...",{'$date': '2025-05-08T11:41:10.780Z'}

In [17]:
action_data = pd.json_normalize(df['actionData'])
df = pd.concat([df.drop(columns=['actionData']), action_data], axis=1)

In [18]:
df.head()

,_id,userWallet,network,protocol,txHash,logId,timestamp,blockNumber,action,__v,...,repayerId,liquidatorId,collateralAmount,collateralAssetPriceUSD,principalAmount,borrowAssetPriceUSD,collateralReserveId,collateralReserveSymbol,principalReserveId,principalReserveSymbol
0,{'$oid': '681d38fed63812d4655f571a'},0x00000000001accfa9cef68cf5371a23025b6d4b6,polygon,aave_v2,0x695c69acf608fbf5d38e48ca5535e118cc213a89e3d6...,0x695c69acf608fbf5d38e48ca5535e118cc213a89e3d6...,1629178166,1629178166,deposit,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,{'$oid': '681aa70dd6df53021cc6f3c0'},0x000000000051d07a4fb3bd10121a343d85818da6,polygon,aave_v2,0xe6fc162c86b2928b0ba9b82bda672763665152b9de9d...,0xe6fc162c86b2928b0ba9b82bda672763665152b9de9d...,1621525013,1621525013,deposit,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,{'$oid': '681d04c2d63812d4654c733e'},0x000000000096026fb41fc39f9875d164bd82e2dc,polygon,aave_v2,0xe2d7eb815c89331a734ed6f204a06c385a1b39040baa...,0xe2d7eb815c89331a734ed6f204a06c385a1b39040baa...,1627118913,1627118913,deposit,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,{'$oid': '681d133bd63812d46551b6ef'},0x000000000096026fb41fc39f9875d164bd82e2dc,polygon,aave_v2,0x0d63a2eacd82b82f868db825ea7385e6bd8d046ee729...,0x0d63a2eacd82b82f868db825ea7385e6bd8d046ee729...,1627773318,1627773318,deposit,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,{'$oid': '681899e4ba49fc91cf2f4454'},0x0000000000e189dd664b9ab08a33c4839953852c,polygon,aave_v2,0x590eabb812c5006a6f4766f44e6e9d3ad0b5b563de69...,0x590eabb812c5006a6f4766f44e6e9d3ad0b5b563de69...,1618845907,1618845907,redeemunderlying,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df.columns

Index(['_id', 'userWallet', 'network', 'protocol', 'txHash', 'logId',
       'timestamp', 'blockNumber', 'action', '__v', 'createdAt', 'updatedAt',
       'type', 'amount', 'assetSymbol', 'assetPriceUSD', 'poolId', 'userId',
       'toId', 'borrowRateMode', 'borrowRate', 'variableTokenDebt',
       'stableTokenDebt', 'callerId', 'useATokens', 'repayerId',
       'liquidatorId', 'collateralAmount', 'collateralAssetPriceUSD',
       'principalAmount', 'borrowAssetPriceUSD', 'collateralReserveId',
       'collateralReserveSymbol', 'principalReserveId',
       'principalReserveSymbol'],
      dtype='object')

In [20]:
df.shape

(100000, 35)

In [23]:
df['action'].unique()

array(['deposit', 'redeemunderlying', 'borrow', 'repay',
       'liquidationcall'], dtype=object)

In [29]:
action_counts = df.groupby(['userWallet', 'action']).size().unstack(fill_value=0).reset_index()

In [31]:
action_counts

action,userWallet,borrow,deposit,liquidationcall,redeemunderlying,repay
0,0x00000000001accfa9cef68cf5371a23025b6d4b6,0,1,0,0,0
1,0x000000000051d07a4fb3bd10121a343d85818da6,0,1,0,0,0
2,0x000000000096026fb41fc39f9875d164bd82e2dc,0,2,0,0,0
3,0x0000000000e189dd664b9ab08a33c4839953852c,0,0,0,17,0
4,0x0000000002032370b971dabd36d72f3e5a7bf1ee,15,250,0,130,4
...,...,...,...,...,...,...
3492,0x06185db89f5c8ef5e5a0abc95c5cb69b54c33f30,0,1,0,0,0
3493,0x06189341e523a52ae10c4bd4a7774371fac1b249,1,4,0,2,0
3494,0x0618c450370822c5cb25ec143a3008230d8e2c12,0,1,0,4,0
3495,0x0618e615c8c9b5efc8c8eadc68be7182bdc455e2,2,13,0,5,2
3496,0x06192f889f17bf2aff238d08d8c26cbcfcc7b45a,48,53,0,46,36

✅ More deposit → Positive impact on score.

✅ More repay → Positive impact.

🚫 More borrow → Neutral or slightly negative impact.

🚫 More redeemunderlying → Neutral or slight negative impact (depends on strategy).

🚨 More liquidationcall → Strong negative impact.

calculating scores

In [32]:
weights = {
    'deposit': 2.0,
    'repay': 1.5,
    'borrow': -1.0,
    'redeemunderlying': -0.5,
    'liquidationcall': -3.0
}

def calculate_score(row):
    score = 0
    for action in weights:
        score += row.get(action, 0) * weights[action]
    return score

action_counts['raw_score'] = action_counts.apply(calculate_score, axis=1)

SyntaxError: invalid syntax (4203619835.py, line 1)